version: "3"
services:
  jobmanager:
    image: flink:${FLINK_VERSION:-1.11.2-scala_2.11}
    container_name: flink-jobmanager
    hostname: jobmanager
    networks:
      flink:
        ipv4_address: 172.18.0.2
        aliases:
          - jobmanager
    extra_hosts:
      - "taskmanager:172.18.0.3"
      - "zookeeper:172.18.0.4"
      - "kafka:172.18.0.5"
    ports:
      - "8081:8081"
    command:
      - bash
      - -c
      - |
        sed -i 's/start-foreground/start/g' /docker-entrypoint.sh
        /docker-entrypoint.sh jobmanager 
        tail -f /docker-entrypoint.sh
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - .:/opt/flink/src

  taskmanager:
    image: flink:${FLINK_VERSION:-1.11.2-scala_2.11}
    container_name: flink-taskmanager
    hostname: taskmanager
    networks:
      flink:
        ipv4_address: 172.18.0.3
        aliases:
          - taskmanager
    extra_hosts:
      - "jobmanager:172.18.0.2"
      - "zookeeper:172.18.0.4"
      - "kafka:172.18.0.5"
    depends_on:
      - jobmanager
    command:
      - bash
      - -c
      - |
        sed -i 's/start-foreground/start/g' /docker-entrypoint.sh
        /docker-entrypoint.sh taskmanager 
        tail -f /docker-entrypoint.sh
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - .:/opt/flink/src

  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION:-3.6.2}
    container_name: flink-zookeeper
    hostname: zookeeper
    networks:
      flink:
        ipv4_address: 172.18.0.4
        aliases:
          - zookeeper
    extra_hosts:
      - "jobmanager:172.18.0.2"
      - "taskmanager:172.18.0.3"
      - "kafka:172.18.0.5"
    ports:
      - 2181:2181
       
  kafka:
    image: wurstmeister/kafka:${KAFKA_VERSION:-2.13-2.6.0}
    container_name: flink-kafka
    hostname: kafka
    networks:
      flink:
        ipv4_address: 172.18.0.5
        aliases:
          - kafka
    extra_hosts:
      - "jobmanager:172.18.0.2"
      - "taskmanager:172.18.0.3"
      - "zookeeper:172.18.0.4"
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CREATE_TOPICS: "metric:2:1"   #kafka启动后初始化一个有2个partition(分区)1个副本名叫metric的topic 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  edge:
    image: darebeat/netcat:latest
    command: tail -f /entrypoint.sh
    container_name: flink-edge
    hostname: edge
    networks:
      flink:
        ipv4_address: 172.18.0.100
        aliases:
          - edge
    extra_hosts:
      - "jobmanager:172.18.0.2"
      - "taskmanager:172.18.0.3"
    ports:
      - "9000:9000"

networks:
  flink:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1