version: '3'
services:
  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION:-3.6.2}
    container_name: flink-zookeeper
    hostname: zookeeper
    networks:
      deploy:
        ipv4_address: 172.10.0.8
        aliases:
          - zookeeper
    # extra_hosts:
    #   - "jobmanager:172.10.0.2"
    #   - "taskmanager:172.10.0.3"
    ports:
      - 2181:2181
       
  kafka:
    image: wurstmeister/kafka:${KAFKA_VERSION:-2.13-2.6.0}
    container_name: flink-kafka
    hostname: kafka
    networks:
      deploy:
        ipv4_address: 172.10.0.9
        aliases:
          - kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CREATE_TOPICS: "test.base:2:1"   #kafka启动后初始化一个有2个partition(分区)1个副本名叫metric的topic 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

networks:
  deploy:
    external: true