version: '3'
services:
  jobmanager:
    image: flink:${FLINK_VERSION:-1.11.2-scala_2.11}
    container_name: flink-jobmanager
    hostname: jobmanager
    networks:
      deploy:
        ipv4_address: 172.10.0.2
        aliases:
          - jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    # command:
    #   - bash
    #   - -c
    #   - |
    #     sed -i 's/start-foreground/start/g' /docker-entrypoint.sh
    #     /docker-entrypoint.sh jobmanager 
    #     touch /opt/flink/log/flink-keep-jobmanager.log
    #     tail -f /opt/flink/log/*
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      # - ./logs/jobmanager/:/opt/flink/log/
      - ./config/flink-jars/:/opt/flink/connector-lib/

  taskmanager:
    image: flink:${FLINK_VERSION:-1.11.2-scala_2.11}
    container_name: flink-taskmanager
    hostname: taskmanager
    networks:
      deploy:
        ipv4_address: 172.10.0.3
        aliases:
          - taskmanager
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    # command:
    #   - bash
    #   - -c
    #   - |
    #     sed -i 's/start-foreground/start/g' /docker-entrypoint.sh
    #     /docker-entrypoint.sh taskmanager 
    #     touch /opt/flink/log/flink-keep-taskmanager.log
    #     tail -f /opt/flink/log/*
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
    # volumes:
    #   - ./logs/taskmanager/:/opt/flink/log/

  mysql:
    image: mysql:5.7
    container_name: flink-mysql
    hostname: mysql
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.4
        aliases:
          - mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=darebeat
      - MYSQL_PASSWORD=mydbsys 
      - MYSQL_DATABASE=test
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./config/mysql-config/my.cnf:/etc/my.cnf

  # pd:
  #   image: pingcap/pd:v3.1.0
  #   container_name: flink-pd
  #   hostname: pd
  #   ports:
  #     - "2379"
  #   volumes:
  #     - ./config/tidb-config/pd.toml:/pd.toml:ro
  #     - ./logs/tidbs:/logs/
  #   networks:
  #     deploy:
  #       ipv4_address: 172.10.0.5
  #       aliases:
  #         - pd
  #   command:
  #     - --name=pd
  #     - --client-urls=http://0.0.0.0:2379
  #     - --peer-urls=http://0.0.0.0:2380
  #     - --advertise-client-urls=http://pd:2379
  #     - --advertise-peer-urls=http://pd:2380
  #     - --initial-cluster=pd=http://pd:2380
  #     - --data-dir=/data/pd
  #     - --config=/pd.toml
  #     - --log-file=/logs/pd.log
  #   restart: on-failure

  # tikv:
  #   image: pingcap/tikv:v3.1.0
  #   container_name: flink-tikv
  #   hostname: tikv
  #   volumes:
  #     - ./config/tidb-config/tikv.toml:/tikv.toml:ro
  #     - ./logs/tidbs:/logs/
  #   command:
  #     - --addr=0.0.0.0:20160
  #     - --advertise-addr=tikv:20160
  #     - --data-dir=/data/tikv
  #     - --pd=pd:2379
  #     - --config=/tikv.toml
  #     - --log-file=/logs/tikv.log
  #   networks:
  #     deploy:
  #       ipv4_address: 172.10.0.6
  #       aliases:
  #         - tikv
  #   depends_on:
  #     - "pd"
  #   restart: on-failure

  # tidb:
  #   image: pingcap/tidb:v4.0.7
  #   container_name: flink-tidb
  #   hostname: tidb
  #   ports:
  #     - "4000:4000"
  #     - "10080:10080"
  #   volumes:
  #     - ./config/tidb-config/tidb.toml:/tidb.toml:ro
  #     - ./logs/tidbs:/logs/
  #   command:
  #     - --store=tikv
  #     - --path=pd:2379
  #     - --config=/tidb.toml
  #     - --log-file=/logs/tidb.log
  #     - --log-slow-query=/logs/tidb_slow.log
  #     - --advertise-address=tidb
  #   networks:
  #     deploy:
  #       ipv4_address: 172.10.0.7
  #       aliases:
  #         - tidb
  #   depends_on:
  #     - "tikv"
  #   restart: on-failure

networks:
  deploy:
    external: true